name: fhir_rest_client
description: A Dart package to describe FHIR REST calls and corresponding client
  to send these requests to a FHIR server
version: 1.0.0
homepage: https://www.evoleen.com
repository: https://github.com/evoleen/fhir_rest_client

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  dio: ^5.5.0+1
  fhir: ^0.12.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.11
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  lints: ^3.0.0
  test: ^1.24.0
